{% set name = "openneuro-py" %}
{% set version = "2021.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 217e1e703505b8cdcc2a9328f56cbff9fa53cdf36393bc57754abb2d66a984b5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - openneuro-py = openneuro.openneuro:cli

requirements:
  host:
    - python
    - pip
  run:
    - python
    - aiofiles
    - httpx >=0.15
    - sgqlc
    - requests
    - tqdm
    - click
    - importlib-metadata  # [py <38]
    - typing-extensions   # [py <38]
    - async_generator     # [py ==36]

test:
  imports:
    - openneuro
  commands:
     # Test the entry point.
    - openneuro-py --version
    - openneuro-py download --dataset=ds000248 --include=CHANGES --verify_size=0

about:
  home: https://github.com/hoechenberger/openneuro-py
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A Python client for OpenNeuro.

extra:
  recipe-maintainers:
    - hoechenberger
