{% set name = "openneuro-py" %}
{% set version = "2021.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63ff8f66f80025b761979e9f91e5fab32c9be89a70f13f6ba8e1b010e226cd24

build:
  number: 1
  skip: true  # [py <37]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - openneuro-py = openneuro.openneuro:cli

requirements:
  host:
    - python
    - pip
  run:
    - python
    - aiofiles
    - httpx >=0.15
    - sgqlc
    - requests
    - tqdm
    - click
    - importlib-metadata  # [py <38]
    - typing-extensions   # [py <38]

test:
  imports:
    - openneuro
  commands:
     # Test the entry point.
    - openneuro-py --version
    - openneuro-py download --dataset=ds000248 --include=CHANGES --verify_size=0

about:
  home: https://github.com/hoechenberger/openneuro-py
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A Python client for OpenNeuro.

extra:
  recipe-maintainers:
    - hoechenberger
