{% set name = "openneuro-py" %}
{% set version = "2024.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 660b92a2f87354df3e29a4fd5ade8adf607bd5bec7e912e55f2b2b50691f381a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - openneuro-py = openneuro._cli:app

requirements:
  build:
    - python >=3.10                          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python  >=3.10
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.10
    - aiofiles
    - httpx >=0.15
    - sgqlc
    - requests
    - tqdm
    - platformdirs
    - typer

test:
  imports:
    - openneuro
  commands:
     # Test the entry point.
    - openneuro-py --version
    - openneuro-py --help
    - openneuro-py download --help
    - openneuro-py download --dataset=ds000248 --include=CHANGES --verify_size=0

about:
  home: https://github.com/hoechenberger/openneuro-py
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A Python client for OpenNeuro.

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
