{% set python_min = "3.10" %}
{% set name = "openneuro-py" %}
{% set version = "2025.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0fcf40f729077a0f3f14397046f5bf84a1daa6ba5797ed1a1f80a15d51e3e92d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - openneuro-py = openneuro._cli:app

requirements:
  build:
    - python >=3.10                          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - aiofiles
    - httpx >=0.15
    - sgqlc
    - requests
    - tqdm
    - platformdirs
    - typer

test:
  requires:
    - python {{ python_min }}
  imports:
    - openneuro
  commands:
     # Test the entry point.
    - openneuro-py --version
    - openneuro-py --help
    - openneuro-py download --help
    - openneuro-py download --dataset=ds000248 --include=CHANGES --no-verify-size

about:
  home: https://github.com/hoechenberger/openneuro-py
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A Python client for OpenNeuro.

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
