{% set name = "openneuro-py" %}
{% set version = "2022.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67dfbeba7983089e6c09dcb0a8305d48fa79fb158004dafda462f8f6511e5310

build:
  number: 0
  skip: true  # [py < 37 or python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - openneuro-py = openneuro.openneuro:cli

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - aiofiles
    - httpx >=0.15
    - sgqlc
    - requests
    - tqdm
    - click
    - importlib-metadata  # [py <38]
    - typing-extensions   # [py <38]

test:
  imports:
    - openneuro
  commands:
     # Test the entry point.
    - openneuro-py --version
    - openneuro-py download --dataset=ds000248 --include=CHANGES --verify_size=0

about:
  home: https://github.com/hoechenberger/openneuro-py
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A Python client for OpenNeuro.

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
